### ISSUE TITLE
Issue importing project

### ISSUE THREAD

**Issue by Gregam3** [Josh-McFarlin/CryptoCompareAPI#1]
Hi Josh,

I've used the maven dependency you've provided in your readme and I'm having issues importing it.
![image](https://user-images.githubusercontent.com/14945621/35391650-2b0adf78-01d7-11e8-8934-4e80e3c8e5bb.png)

**Comment by Josh-McFarlin** [comment]
First snapshot released, check the readme for the new groupId.
